// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "MA0066:Hash table unfriendly type is used in a hash table", Justification = "<Pending>", Scope = "member", Target = "~F:it.Countries.countriesByUtcOffset")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1810:Initialize all static fields in 'TryRomanActions' when those fields are declared and remove the explicit static constructor", Justification = "<Pending>", Scope = "member", Target = "~M:it.Actions.TryRomanActions.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:ConvertActions is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "<Pending>", Scope = "type", Target = "~T:it.Actions.ConvertActions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:CountdownActions is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "<Pending>", Scope = "type", Target = "~T:it.Actions.CountdownActions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:DeviceActions is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "<Pending>", Scope = "type", Target = "~T:it.Actions.DeviceActions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:RandomActions is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "<Pending>", Scope = "type", Target = "~T:it.Actions.RandomActions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:TimezoneActions is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "<Pending>", Scope = "type", Target = "~T:it.Actions.TimezoneActions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:TryRomanActions is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "<Pending>", Scope = "type", Target = "~T:it.Actions.TryRomanActions")]